data_path = "/home/tristan/road_project/workspace/data/RoadDamage/train/"
submission_data_path = "/home/tristan/road_project/workspace/data/RoadDamage/test1/"
submission_path = "/home/tristan/road_project/workspace/Damage Detection/submissions/"
model_path = "/home/tristan/road_project/workspace/Damage Detection/Detection/Torchvision/Checkpoints"
LOG_DIR = "/home/tristan/road_project/workspace/tensorboard"